// Mocks generated by Mockito 5.0.3 from annotations
// in grab_clone/test/bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:grab_clone/models/discovery_model.dart' as _i4;
import 'package:grab_clone/repository/discovery_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [DiscoveryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoveryRepository extends _i1.Mock
    implements _i2.DiscoveryRepository {
  MockDiscoveryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.DiscoveryModel>> getDiscoveryList() =>
      (super.noSuchMethod(Invocation.method(#getDiscoveryList, []),
              returnValue: Future.value(<_i4.DiscoveryModel>[]))
          as _i3.Future<List<_i4.DiscoveryModel>>);
}
